services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: ksaumu-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.28.0-alpine
    container_name: ksaumu-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: ksaumu-db
    image: mysql:8.0.43
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ksaumu_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  db_data:
